version: '3.5'

services:
  metabase:
    image: metabase/metabase
    ports:
      - "3000:3000"
    volumes:
      - metabase-data:/metabase-data
    env_file:
      - .env
    depends_on:
      - postgresql

  postgresql:
    image: "postgres:14.2"
    env_file:
      - .env
    volumes:
      - postgresql-data:/var/lib/postgresql/data

volumes:
  metabase-data:
  postgresql-data: